console.log(Math.PI)
console.log(Math.E)
console.log(Math.SQRT2)
console.log(Math.log2)
console.log(Math.round(2.14))
console.log(Math.trunc(2.25))
console.log(Math.ceil(14.25))
console.log(Math.trunc(Math.random()*7))
let d=new Date()
console.log(d.get date()."/",d.getMonth()+1,"/",d.getFullyear())
console.log(d.getDay()+1)